export const REFERRAL_STATUS = {
    IN_PROCESS: 'IN PROCESS',
    CONTACTED: 'CONTACTED',
    RESERVED: 'RESERVED',
    SIGNED_DEED: 'SIGNED_DEED',
    ACCEPTED: 'ACCEPTED',
    PAID: 'PAID',
    CANCELED: 'CANCELED'
}
export type REFERRAL_STATUS = typeof REFERRAL_STATUS[keyof typeof REFERRAL_STATUS]

export const COLORS = {
    REFERRAL_ICON_WAITING: '#f4d859',
    REFERRAL_BACKGROUND_WAITING: '#fcf4ce',
    REFERRAL_BACKGROUND_FOLLOWUP: '#f2c992',
    REFERRAL_ICON_FOLLOWUP: '#fb9305',
    REFERRAL_ICON_APPROVED: '#114039',
    REFERRAL_BACKGROUND_APPROVED: '#22D3BC',
    REFERRAL_ICON_REJECTED: '#D82A43',
    REFERRAL_BACKGROUND_REJECTED: '#FFA9B5',
}
export type COLORS = typeof COLORS[keyof typeof COLORS]