import { Bonus, Companie } from "../../../redux/fetch/responses"

export interface InputProps {
    ref: any,
    name: string,
    setName: (name: string) => void,
    model: string,
    setModel: (model: string) => void,
    preSalePrice: string,
    setPreSalePrice: (preSalePrice: string) => void,
    rentPriceApproximate: string,
    setRentPriceApproximate: (rentPriceApproximate: string) => void,
    resalePriceApproximate: string,
    setResalePriceApproximate: (resalePriceApproximate: string) => void,
    preSaleDate: string,
    setPreSaleDate: (preSaleDate: string) => void,
    premisesDeliveryDate: string,
    setPremisesDeliveryDate: (premisesDeliveryDate: string) => void,
    description: string,
    setDescription: (description: string) => void,
    idBonus: string,
    setIdBonus: (idBonus: string) => void,
    idCompany: string,
    setIdCompany: (idCompany: string) => void,
    bonuses: Bonus[],
    companies: Companie[],
}